В задании №2 постарался учесть все возможные строки.
Про сохранение результата не было ничего сказано, поэтому просто прогоняю построчно до конца, все работает
В заданиях №3 м №4 не понял зачем прятать декоратор т.к. callback.__name__ возвращает имя функции, а не wrapper'а.

В задании №4 не понял, как можно пробросить переменную наружу:
В задании указано при выведении информации об ошибке указать значение которое её вызвало.
Я задаю переменную и при вызове функции обрабатываю ошибку, указывая там переменную:
a = -5, при обработке в f-строке {a}

Если обрабатывать ошибку внутри декоратора, будет дополнительно возвращаться None при вызове функции:
ValueError: wrong val -5
None

Можно ли как то обрабатывать эту ошибку при вызове функции, но не создавая переменную, а получать значения из args?
